### ISSUE TITLE
No such channel error in Konversation

### ISSUE THREAD

**Issue by avandecreme** [gitterHQ/irc-bridge#17]
Every minute I get that error in Konversation:
```[Error] No such channel: No such channel.```

When debugging it appears Konversation is sending a WHO myusername request.
In the server log, I get the following error:

```
  irc-client Rx: WHO avandecreme +1s
  irc-client Rx: WHO #openseadragon/openseadragon +38ms
Error listing users for  avandecreme [Error: 403 {"error":"Permission denied"}]
Error: 403 {"error":"Permission denied"}
    at IncomingMessage.<anonymous> (irc-bridge/node_modules/node-gitter/lib/client.js:90:22)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
  irc-client Tx: :irc.gitter.im 403 avandecreme :No such channel +165ms
```

I can reproduce the same error by sending the WHO request myself. However, if I send a WHO otherusername, the server seems to try to reply the correct result but my client cannot interpret it.

So I am not sure whether this is a Konversation or irc-bridge bug (a little bit of both?).

**Comment by avandecreme** [comment]
After consultation with the Konversation developers, the client is sending the WHO requests to keep the client own hostmask up to date. This is needed for outbound message wrapping calculations.
