### ISSUE TITLE
Consider adding engines to package.json

### ISSUE THREAD

**Issue by jimschubert** [gitterHQ/irc-bridge#7]
Dependencies don't install for me in OS X for node versions 0.12.0 or 0.11.9, but do for version 0.10.20. The problem was memwatch, which I've had similar issues with in the past.

Maybe a quick fix:
```
"engines": { "node": "~0.10.20" },
```

Here's the error, truncated a bit.

```
$ npm install
npm http GET https://registry.npmjs.org/memwatch
npm http 304 https://registry.npmjs.org/memwatch

> memwatch@0.2.2 install /Volumes/Extra/projects/irc-bridge/node_modules/memwatch
> node-gyp rebuild

  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
In file included from ../src/heapdiff.cc:5:
../src/heapdiff.hh:14:35: error: expected class name
    class HeapDiff : public node::ObjectWrap
                                  ^
../src/heapdiff.hh:19:49: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New( const v8::Arguments& args );
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/jim/.node-gyp/0.11.9/deps/v8/include/v8.h:141:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/heapdiff.cc:5:
../src/heapdiff.hh:20:49: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> End( const v8::Arguments& args );
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/jim/.node-gyp/0.11.9/deps/v8/include/v8.h:141:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/heapdiff.cc:30:34: error: member initializer 'ObjectWrap' does not name a non-static data member or base class
heapdiff::HeapDiff::HeapDiff() : ObjectWrap(), before(NULL), after(NULL),
                                 ^~~~~~~~~~~~
...
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/memwatch/src/heapdiff.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:101:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:827:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/Extra/projects/irc-bridge/node_modules/memwatch
gyp ERR! node -v v0.11.9
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm ERR! memwatch@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memwatch@0.2.2 install script.
npm ERR! This is most likely a problem with the memwatch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls memwatch
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.1.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Volumes/Extra/projects/irc-bridge
npm ERR! node -v v0.11.9
npm ERR! npm -v 1.3.15
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Volumes/Extra/projects/irc-bridge/npm-debug.log
npm ERR! not ok code 0
```

**Comment by malditogeek** [comment]
Good point. Added the current engine. Will investigate why memwatch fails on 0.12.x tho. Thx!

**Comment by suprememoocow** [comment]
memwatch is broken in node 0.12 and io.js due to changes in bindings APIs: https://github.com/lloyd/node-memwatch/issues/62

I recently removed the dependency from the main Gitter webapp in preparation for a 0.12 upgrade for the same reason.

**Comment by malditogeek** [comment]
Is there a replacement for memwatch available yet?

**Comment by suprememoocow** [comment]
Doesn’t look like it. 

Fancy creating a pull-request to switch the native bindings for NAN bindings? https://github.com/rvagg/nan <https://github.com/rvagg/nan>

**Comment by Brightergy-LaurieFletcher** [comment]
does this mean i need to install 0.10.20?

**Comment by jimschubert** [comment]
You can use [nave](https://github.com/isaacs/nave) to manage different node environments.

You can create a node environment called gitterhq that runs 0.10.20:

```
npm install -g nave
nave use gitterhq 0.10.20
npm install -d
```

This node environment runs as a subshell. When you exit the shell, you'll revert to your main node version and 0.10.20 with all its dependencies will still exist under `~/.nave`. To get back to the npm/node version, run `nave use gitterhq 0.10.20` again.  If you run the command with a different node version (e.g. `nave use gitterhq 0.11.0`), nave will download the newer version and link it to the installation point. I *believe* that anything you install 'globally' in this subshell will be installed under the node environment subshell's path under `~/.nave`.

I'd consider this a temporary workaround until memwatch is updated.
